uint8        type
int32        intensity
float32      max_z
float32      min_z
float32      average_z
float32      delta_z

uint8        layers_num
uint32       points_num
uint32       startlaser_index
uint32       endlaser_index	
uint32       endpoint_index
uint32       startpoint_index

bool         up_link
bool         down_link
bool         left_link
bool         right_link

float32        ground_z
float32        ground_xy
float32        grad_m
float32        grad_b   
